import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  loadDevMessages();
  loadErrorMessages();
  return (
    <html lang="en">
      <body className="flex justify-center items-center">
        <div className="flex min-h-screen flex-col items-center max-w-screen-2xl justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
